server:
  port: 8001
  servlet:
    context-path: /member
spring:
  application:
    name: member
  datasource:
    url: jdbc:mysql://122.51.61.24:3306/user?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: user
    password: KE4btJa8cx8HxByj
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
logging:
  level.org.phy.member.mapper=trace